# Generated by Django 3.1 on 2020-08-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200824_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='no_of_products',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
