# Generated by Django 3.1 on 2020-08-25 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200825_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='no_of_products',
        ),
    ]
