# Generated by Django 3.1 on 2020-08-27 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customer_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
    ]
