# Generated by Django 3.1 on 2020-08-27 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200827_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='profile_picture',
            new_name='profile_pic',
        ),
    ]
